plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url "https://repo.papermc.io/repository/maven-public/" }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.12.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    compileOnly libs.paper.api
    compileOnly libs.paper.advntr
    compileOnly libs.paper.minimessage

    api project(":commons")
    compileOnly libs.reflections
    compileOnly libs.netty.buffer

    testImplementation libs.gson
    testImplementation libs.guava
    testImplementation libs.netty.buffer
    testImplementation libs.compile.testing
    testRuntimeOnly libs.paper.api
}

test {
    useJUnitPlatform()
}